{
 "title": "OTRS-Exporter-OTRS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ticket quantity changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(otrs_ticket_total[5m])",
     "legendFormat": "{{host}} => {{queue}} {{status}}"
    }
   ]
  },
  {
   "title": "article quantity changes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(otrs_article_total[5m])",
     "legendFormat": "{{host}} => {{queue}} {{status}}"
    }
   ]
  },
  {
   "title": "income mail quantity changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(otrs_income_mail_total[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "outgoing mail quantity changes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(otrs_outgoing_mail_total[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "logs quantity changes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(otrs_logs_total[5m])", "legendFormat": "{{host}} => {{priority}}" }
   ]
  }
 ]
}