{
 "title": "OTRS-Exporter-Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "http processes resident memory mb",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_process_resident_memory_bytes/1048576",
     "legendFormat": "{{host}} => pid-{{worker}}"
    }
   ]
  },
  {
   "title": "http processes cpu time changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_process_cpu_seconds_total[1m])",
     "legendFormat": "{{host}} => pid-{{worker}}"
    }
   ]
  },
  {
   "title": "CACHE OPERATIONS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "cache_operations", "legendFormat": "{{host}} => {{operation}}" }
   ]
  }
 ]
}