{
 "title": "OTRS-Exporter-Daemon",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "daemon processes resident memory (mb)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "daemon_process_resident_memory_bytes/1048576",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "daemon processes cpu time in seconds changes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(daemon_process_cpu_seconds_total[1m])",
     "legendFormat": "{{host}} => ( {{name}}, pid-{{worker}} )"
    }
   ]
  },
  {
   "title": "daemon tasks execution time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "daemon_subworkers_task_last_execution_time",
     "legendFormat": "{{host}} => {{task_handler_module}} -> {{task_name}}"
    }
   ]
  },
  {
   "title": "daemon tasks total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "daemon_subworkers_total",
     "legendFormat": "{{host}} => {{task_handler_module}} -> {{task_name}}"
    }
   ]
  }
 ]
}